name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Installer les dépendances
      run: npm install

    - name: Construire le site
      run: npm run build  # Assurez-vous d'ajuster cette commande en fonction de votre configuration

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Déployer sur GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # Branche GitHub Pages
